export const UPDATE_TEXT = "UPDATE_TEXT";
export const UPDATE_PATH = "UPDATE_PATH";
export const REMOVE_LINE = "REMOVE_LINE";
export const CREATE_LINE = "CREATE_LINE";
export const ADD_LINE_VERSION = "ADD_LINE_VERSION";

export const REMOVE_LINE_AT_LOCATION = "REMOVE_LINE_AT_LOCATION";
export const UPDATE_TEXT_AT_LOCATION = "UPDATE_TEXT_AT_LOCATION_AND_VERSION";